import { useEffect, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { IconShield, IconCheck, IconCopy, IconAlertTriangle } from './Icons';
import type { ScanProgressEvent, ViolationAlert, IndexGap, CircularDepsResult } from '../types';

const cardVariants = {
  hidden: { opacity: 0, y: 10, scale: 0.97 },
  visible: (i: number) => ({
    opacity: 1, y: 0, scale: 1,
    transition: { delay: Math.min(i * 0.04, 0.28), duration: 0.28, ease: [0.25, 0, 0.2, 1] as [number, number, number, number] },
  }),
  exit: { opacity: 0, x: -16, transition: { duration: 0.18 } },
};

type Tab = 'violations' | 'index-gaps' | 'circular-deps';

interface ViolationPanelProps {
  violations: ViolationAlert[];
  scanProgress: ScanProgressEvent | null;
  isConnected: boolean;
  indexGaps: IndexGap[];
  circularDeps: CircularDepsResult;
  activeTab: Tab;
  onTabChange: (tab: Tab) => void;
}

export default function ViolationPanel({
  violations,
  scanProgress,
  isConnected,
  indexGaps,
  circularDeps,
  activeTab,
  onTabChange,
}: ViolationPanelProps) {
  const feedRef = useRef<HTMLDivElement>(null);
  const cardRefs = useRef<(HTMLDivElement | null)[]>([]);
  const [expandedViolation, setExpandedViolation] = useState<number | null>(null);
  const [expandedGap, setExpandedGap] = useState<number | null>(null);
  const [copiedGapIndex, setCopiedGapIndex] = useState<number | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);

  useEffect(() => {
    if (feedRef.current) feedRef.current.scrollTop = feedRef.current.scrollHeight;
  }, [violations]);

  // After card expands, scroll so the FULL card (including fix section) is visible
  useEffect(() => {
    if (expandedViolation === null) return;
    // Wait for the layout animation to finish before measuring
    const timer = setTimeout(() => {
      const card = cardRefs.current[expandedViolation];
      const feed = feedRef.current;
      if (!card || !feed) return;
      const feedRect = feed.getBoundingClientRect();
      const cardRect = card.getBoundingClientRect();
      // How many px does the card bottom exceed the feed's visible bottom?
      const overflow = cardRect.bottom - feedRect.bottom;
      if (overflow > 0) {
        feed.scrollBy({ top: overflow + 12, behavior: 'smooth' });
      }
    }, 280); // after the 180ms layout animation + buffer
    return () => clearTimeout(timer);
  }, [expandedViolation]);

  const percent = scanProgress && scanProgress.totalTables > 0
    ? Math.round((scanProgress.tablesScanned / scanProgress.totalTables) * 100)
    : 0;

  const sevClass = (sev: string) => {
    if (sev === 'HIGH')   return 'sev-high';
    if (sev === 'MEDIUM') return 'sev-med';
    return 'sev-low';
  };

  const handleCopyGap = async (sql: string, idx: number) => {
    await navigator.clipboard.writeText(sql);
    setCopiedGapIndex(idx);
    setTimeout(() => setCopiedGapIndex(null), 2000);
  };

  const handleCopyAll = async () => {
    const script = [
      '-- Missing FK indexes — generated by QueryMesh',
      '-- Apply with: psql -f missing-indexes.sql',
      '',
      ...indexGaps.map((g) => g.suggestedIndex),
    ].join('\n');
    await navigator.clipboard.writeText(script);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  return (
    <div className="violation-panel">
      {/* Tab bar */}
      <div className="panel-tabs">
        <button
          className={`panel-tab ${activeTab === 'violations' ? 'active' : ''}`}
          onClick={() => onTabChange('violations')}
        >
          <IconShield size={11} />
          Violations
          {violations.length > 0 && (
            <span className="panel-tab-badge panel-tab-badge--danger">{violations.length}</span>
          )}
        </button>
        <button
          className={`panel-tab ${activeTab === 'index-gaps' ? 'active' : ''}`}
          onClick={() => onTabChange('index-gaps')}
        >
          Idx Gaps
          {indexGaps.length > 0 && (
            <span className="panel-tab-badge panel-tab-badge--warning">{indexGaps.length}</span>
          )}
        </button>
        <button
          className={`panel-tab ${activeTab === 'circular-deps' ? 'active' : ''}`}
          onClick={() => onTabChange('circular-deps')}
        >
          Cycles
          {circularDeps.hasCycles && (
            <span className="panel-tab-badge panel-tab-badge--warning">{circularDeps.cycles.length}</span>
          )}
        </button>

        <div className="panel-tab-spacer" />

        <div className="conn-status">
          <span className={`conn-dot ${isConnected ? 'connected' : 'disconnected'}`} />
          {isConnected ? 'Live' : 'Offline'}
        </div>
      </div>

      {/* ── Violations tab ── */}
      {activeTab === 'violations' && (
        <>
          {scanProgress?.status === 'SCANNING' && (
            <div className="scan-progress">
              <div className="scan-progress-header">
                <span className="scan-current-table">{scanProgress.currentTable}</span>
                <span className="scan-percent">{percent}%</span>
              </div>
              <div className="progress-track">
                <div className="progress-fill" style={{ width: `${percent}%` }} />
              </div>
              <div className="scan-stats">
                <span>{scanProgress.tablesScanned} / {scanProgress.totalTables} tables</span>
                {scanProgress.violationsFound > 0 && (
                  <span className="scan-violation-count">{scanProgress.violationsFound} found</span>
                )}
              </div>
            </div>
          )}

          {scanProgress?.status === 'COMPLETE' && (
            <div className="scan-complete">
              <IconCheck size={13} />
              Scan complete — {scanProgress.violationsFound}{' '}
              {scanProgress.violationsFound === 1 ? 'violation' : 'violations'} found
            </div>
          )}

          <div className="violation-feed" ref={feedRef}>
            {violations.length === 0 ? (
              <div className="feed-empty">
                <div className="feed-empty-icon"><IconShield size={18} /></div>
                <p>No violations detected</p>
                <p className="feed-empty-hint">Run a scan to check FK integrity</p>
              </div>
            ) : (
              <AnimatePresence initial={false}>
                {violations.map((v, i) => (
                  <motion.div
                    key={`${v.table}-${v.column}-${i}`}
                    custom={i}
                    variants={cardVariants}
                    initial="hidden"
                    animate="visible"
                    exit="exit"
                    layout
                    className={`violation-card ${sevClass(v.severity)}`}
                    ref={(el: HTMLDivElement | null) => { cardRefs.current[i] = el; }}
                    onClick={() => setExpandedViolation(expandedViolation === i ? null : i)}
                  >
                    <div className="violation-card-top">
                      <span className={`sev-pill ${sevClass(v.severity)}`}>{v.severity}</span>
                      <span className="violation-table-name">{v.table}</span>
                      <span className="violation-col-name">.{v.column}</span>
                    </div>
                    <div className="violation-card-body">
                      <div className="violation-meta">
                        <div className="vmeta-row">
                          <span className="vmeta-label">Orphaned</span>
                          <span className="vmeta-val danger">{v.orphanedRows} rows</span>
                        </div>
                        <div className="vmeta-row">
                          <span className="vmeta-label">Ref table</span>
                          <span className="vmeta-val">{v.referencedTable}</span>
                        </div>
                      </div>
                    </div>
                    <AnimatePresence>
                      {expandedViolation === i && (
                        <motion.div
                          className="violation-fix"
                          key="fix"
                          initial={{ opacity: 0, y: -4 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -4 }}
                          transition={{ duration: 0.18, ease: [0.25, 0, 0.2, 1] }}
                        >
                          <span className="fix-label">Suggested fix</span>
                          <code className="fix-code">{v.suggestedFix}</code>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </motion.div>
                ))}
              </AnimatePresence>
            )}
          </div>
        </>
      )}

      {/* ── Index Gaps tab ── */}
      {activeTab === 'index-gaps' && (
        <div className="index-gaps-pane">
          {indexGaps.length === 0 ? (
            <div className="feed-empty">
              <div className="feed-empty-icon feed-empty-icon--success"><IconCheck size={18} /></div>
              <p>All FK columns are indexed</p>
              <p className="feed-empty-hint">No missing indexes detected — good shape</p>
            </div>
          ) : (
            <>
              <div className="gaps-toolbar">
                <span className="gaps-summary">
                  {indexGaps.length} unindexed FK {indexGaps.length === 1 ? 'column' : 'columns'}
                </span>
                <button className="copy-all-btn" onClick={handleCopyAll}>
                  {copiedAll ? <IconCheck size={11} /> : <IconCopy size={11} />}
                  {copiedAll ? 'Copied' : 'Copy All'}
                </button>
              </div>

              <div className="gaps-list">
                {indexGaps.map((gap, i) => (
                  <motion.div
                    key={`${gap.table}-${gap.column}`}
                    custom={i}
                    variants={cardVariants}
                    initial="hidden"
                    animate="visible"
                    layout
                    className={`gap-card ${sevClass(gap.severity)}`}
                  >
                    <div
                      className="gap-card-header"
                      onClick={() => setExpandedGap(expandedGap === i ? null : i)}
                    >
                      <div className="gap-card-left">
                        <span className={`sev-pill ${sevClass(gap.severity)}`}>{gap.severity}</span>
                        <span className="gap-table">{gap.table}</span>
                        <span className="gap-col">.{gap.column}</span>
                      </div>
                      <div className="gap-card-right">
                        <span className="gap-rows">{gap.estimatedRows.toLocaleString()} rows</span>
                        <span className="gap-expand-caret">{expandedGap === i ? '−' : '+'}</span>
                      </div>
                    </div>
                    <div className="gap-ref">
                      references <span className="gap-ref-table">{gap.referencedTable}</span>
                    </div>
                    {expandedGap === i && (
                      <motion.div
                        className="gap-sql-block"
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.2, ease: [0.25, 0, 0.2, 1] }}
                        style={{ overflow: 'hidden' }}
                      >
                        <code className="gap-sql">{gap.suggestedIndex}</code>
                        <button
                          className="gap-copy-btn"
                          onClick={(e) => { e.stopPropagation(); handleCopyGap(gap.suggestedIndex, i); }}
                        >
                          {copiedGapIndex === i ? <IconCheck size={10} /> : <IconCopy size={10} />}
                          {copiedGapIndex === i ? 'Copied' : 'Copy'}
                        </button>
                      </motion.div>
                    )}
                  </motion.div>
                ))}
              </div>
            </>
          )}
        </div>
      )}

      {/* ── Circular Deps tab ── */}
      {activeTab === 'circular-deps' && (
        <div className="circular-deps-pane">
          {!circularDeps.hasCycles ? (
            <div className="feed-empty">
              <div className="feed-empty-icon feed-empty-icon--success"><IconCheck size={18} /></div>
              <p>No circular dependencies</p>
              <p className="feed-empty-hint">All FK relationships are acyclic</p>
            </div>
          ) : (
            <>
              <div className="gaps-toolbar">
                <span className="gaps-summary">
                  {circularDeps.cycles.length} circular {circularDeps.cycles.length === 1 ? 'dependency' : 'dependencies'} detected
                </span>
              </div>

              <div className="gaps-list">
                {circularDeps.cycles.map((cycle, i) => (
                  <motion.div
                    key={i}
                    custom={i}
                    variants={cardVariants}
                    initial="hidden"
                    animate="visible"
                    className="cycle-card"
                  >
                    <div className="cycle-card-header">
                      <span className="sev-pill sev-high">HIGH</span>
                      <span className="cycle-card-label">Circular FK</span>
                    </div>

                    {/* Path chain */}
                    <div className="cycle-path">
                      {cycle.path.map((node, j) => (
                        <span key={j} className="cycle-path-item">
                          <span className="cycle-chain-node">{node}</span>
                          {j < cycle.path.length - 1 && (
                            <span className="cycle-chain-arrow">→</span>
                          )}
                        </span>
                      ))}
                    </div>

                    {/* FK constraints in cycle */}
                    <div className="cycle-edges">
                      {cycle.edges.map((edge, j) => (
                        <div key={j} className="cycle-edge-row">
                          <span className="cycle-edge-from">{edge.from}</span>
                          <span className="cycle-edge-arrow">→</span>
                          <span className="cycle-edge-to">{edge.to}</span>
                          <span className="cycle-edge-constraint">{edge.constraint}</span>
                        </div>
                      ))}
                    </div>

                    {/* Risk explanation */}
                    <div className="cycle-explanation">
                      <IconAlertTriangle size={11} />
                      {cycle.explanation}
                    </div>
                  </motion.div>
                ))}
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}
