server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/querymesh_demo
    username: postgres
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    com.querymesh: DEBUG
    org.springframework.web: INFO
